config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  Rails.application.routes.draw do
    post 'events/new', to: 'events#create'
    root 'users#index'
    get '/signin', to: 'sessions#new'
    post '/signin', to: 'sessions#create'
    delete '/signout', to: 'sessions#destroy'
    resources :users
    resources :events
    resources :invitations
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
# frozen_string_literal: true

class Event < ApplicationRecord
  belongs_to :creator, foreign_key: :creator_id, class_name: 'User'
  validates :title, presence: true
  validates :description, presence: true
  validates :date, presence: true
  has_many :invitations, foreign_key: :attended_event_id
  has_many :attendees, through: :invitations, source: :attendee

  scope :past, -> { where('date < :current_time', current_time: DateTime.now) }
  scope :upcoming, -> { where('date >= :current_time', current_time: DateTime.now) }
end

app/models/invitation.rb
# frozen_string_literal: true

class Invitation < ApplicationRecord
  belongs_to :attended_event, class_name: 'Event'
  belongs_to :attendee, class_name: 'User'
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  validates :password_digest, presence: true, length: { minimum: 6 }, allow_nil: true
  validates :name, presence: true
  validates :email, presence: true

  has_many :created_events, foreign_key: 'creator_id', class_name: 'Event'
  has_many :invitations, foreign_key: :attendee_id
  has_many :attended_events, through: :invitations, source: :attended_event

  def upcoming_events
    attended_events.where('date >= :current_time', current_time: DateTime.now)
  end

  def previous_events
    attended_events.where('date < :current_time', current_time: DateTime.now)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  def log_in(user)
    session[:user_id] = user.id
    @current_user = user
    redirect_to user
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/controllers/events_controller.rb
# frozen_string_literal: true

class EventsController < ApplicationController
  def index
    @events = Event.all
    @upcoming = Event.upcoming
    @past = Event.past
    @current_user = current_user
  end

  def new
    @event = Event.new
    @current_user = current_user
  end

  def create
    @event = current_user.created_events.build(event_params)
    if @event.save
      redirect_to current_user
    else
      render 'new'
    end
  end

  def show
    @event = Event.find(params[:id])
    @current_user = current_user
    @checked = (@current_user == @event.creator || @event.attendees.include?(@current_user)) && logged_in?
    @users = User.all
    @invitation = current_user.invitations.build if logged_in?
    @invited = @event.attendees
  end

  private

  def event_params
    params.require(:events).permit(:title, :description, :date)
  end
end

app/controllers/invitations_controller.rb
# frozen_string_literal: true

class InvitationsController < ApplicationController
  def create
    @invitation = current_user.invitations.build(invitation_params)
    event = Event.find(params['invitation']["attended_event_id"])
    if @invitation.save
      flash[:success] = 'Invitation sent!'
      redirect_to event
    else
      flash.now[:danger] = 'There was a problem with your invite. Try again.'
      redirect_to events_index_url
    end
  end

  private

  def invitation_params
    params.require(:invitation).permit(:attendee_id, :attended_event_id, :host_id)
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by(email: params[:session][:name])
    if user
      log_in(user)
    else
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    flash[:success] = 'Successfully logged out!'
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def index
    @current_user = current_user
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to signin_path
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @invitations = @user.invitations
    @events = @user.created_events
    @invites = @user.attended_events
    @current_user = current_user
    @upcoming_events = @user.upcoming_events
    @previous_events = @user.previous_events
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password_digest)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
# frozen_string_literal: true

module EventsHelper
end

app/helpers/invitation_helper.rb
# frozen_string_literal: true

module InvitationHelper
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/events/create.html.erb
<h1>Events#create</h1>
<p>Find me in app/views/events/create.html.erb</p>

app/views/events/index.html.erb
<div class="eventHead">
        <% if @current_user.nil? %>
        <%= render 'layouts/header2' %>
        
        <% else %>
        <%= render 'layouts/headings' %>
        <% end %>
</div>

<div class="index">

<div class="upcoming">
        <% if !@past.empty? %>
        <h2>These are the past events</h2>
        <ul>
    
            <% @past.each do |event| %>
        
            <li><%= link_to event.title , event %></li>
        
            <% end %>
    
        </ul>
    <% end %>
</div>
       

 
<div>
        <% if !@upcoming.empty? %>
        <h2 >These are the upcoming events</h2>
        <ul>
    
            <% @upcoming.each do |event| %>
        
            <li><%= link_to event.title , event %></li>
        
            <% end %>
        </ul>
        <% end %>
        
</div>


<% if @past.empty? && @upcoming.empty? %>
<h3> There are no created events,be the first to create events</h3> 
<% end %>

</div>

app/views/events/new.html.erb
<% if @current_user.nil? %>
<%= render 'layouts/header2' %>

<% else %>
<%= render 'layouts/headings' %>
<% end %>

<div class="signup">
    <div class="form-group">
        <%= form_for(:events) do |f| %>
        <%= f.label :title, "Name of the event" %>
        <%= f.text_field :title ,class: 'form-control' %> <br>
      
        <%= f.label :description, "Event description" %>
        <%= f.text_area :description ,class: 'form-control' %> <br>
      
        <%= f.label :date, "Date of the event"  %>
        <%= f.date_field :date ,class: 'form-control' %>
        <br>
        <%= f.submit "Create Event" ,class: 'btn btn-primary'%>
      <% end %>
    </div>
    
</div>

app/views/events/show.html.erb
<% if @current_user.nil? %>
<%= render 'layouts/header2' %>

<% else %>
<%= render 'layouts/headings' %>
<% end %>
<div class="eventshow">
		<h2> Event: <%= @event.title%> </h2>

		<p> This event was created by  <b class="name"><%= @event.creator.name.capitalize %></b> </p>
		<br>
		<h3 class="desc">Event Description</h3>
		<p> <%= @event.description %> </p>
		<% if @invited.empty? %>
		<p>No invitations made</p>
		<% else %>
		<% if @event.date > DateTime.now %>
		<p> <b> The following people have been invited: </b></p>
		<% else %>
		<p> <b> The following people were invited </b></p>
        <% end %>
		
		<br>
		<ul class='attendees'>
			
				<% @event.attendees.each do |attendee| %>
				<li><span><%= attendee.name %> </span></li>
				<% end %>
			</ul>	
			
			<% end %>
		</div>
			<div class="signup">
					<div class="form-group">
							<% if @checked %>
							<%= form_for(@invitation) do |f| %>
							<%= f.hidden_field :attended_event_id, value: @event.id %>
							<%= f.hidden_field :host_id, value: @current_user.id %>
							<%= f.label :attendee_id, 'Invite:' %>
							<%= f.select :attendee_id, options_for_select(@users.map do |user|
													   [user.name, user.id]
														   end),
																					{ :prompt => 'Select friend' }, class: 'form-control' %>
							<%= f.submit 'Invite' , class: 'btn btn-primary' %>
						<% end %>
						<% end %>
					</div>
					
			</div>
		

app/views/layouts/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<div class="intro2">
    <b>EventRite</b> - An app that lets you plan your events, put them into your calendar,
    invite the people you want and manage all intricacies.
</div>

app/views/layouts/_header2.html.erb
<div class="nav">
    <div class='logo'>  <a class='li'> EventRiteApp </a></div>
    <div>
            <%= link_to 'Home', root_path, class: 'li check' %>
            <%= link_to 'Sign In', signin_path, class: 'li check' %>
      
            <%= link_to 'Sign Up', new_user_url, class: 'li check' %>
            <%= link_to 'Events', events_url, class: 'li check' %> 

    </div>
        

</div>
    
          

app/views/layouts/_headings.html.erb
<div class="nav">
    <div class='logo'>  <a class='li'> EventRiteApp </a></div>
    <div>
        <%= link_to 'Home', root_path, class: 'li check' %>
        <%= link_to  "Profile", @current_user, class: 'li check' %>
        <%= link_to 'Events', events_url, class: 'li check' %>  
       <%= link_to  "New event", events_new_url, class: 'li check' %>
       <%= link_to  "Sign Out", signout_path , method: :delete , class: 'li check' %></h2> 
    </div>
    
</div>
       
      
    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EventRitte</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Liu+Jian+Mao+Cao&family=Oswald:wght@500&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js" integrity="sha384-6khuMg9gaYr5AxOqhkVIODVIvm9ynTT5J4V1cfthmT+emCG6yVmEZsRHdxlotUnm" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <script>
      const check = document.querySelectorAll('.check')
      
      check.forEach(element => {
        element.addEventListener("mouseover", function(e) {
       e.target.classList.add('animated', 'heartBeat','red');
       console.log(check.className)
      })
      element.addEventListener('mouseout',function(e) {
       e.target.classList.remove('red','animated', 'heartBeat')
      })
      });
      
     </script>
  </body>
  
</html>

app/views/users/index.html.erb
<div class="body">
    <% if @current_user.nil? %>
<%= render 'layouts/header2' %>

<% else %>
<%= render 'layouts/headings' %>
<% end %>
<div class="pinky">
    <div class="own">
    <p>  CREATE YOUR EVENTS </p> 
    <p>  INVITE YOUR FRIENDS </p>  
    </div>
    <div class="own own2 ">
        <p>  CHECK OUT THE LATEST EVENTS </p> 
         
    </div>
    <div class="own">
        <p>  RECEIVE INVITATIONS </p> 
        <p>  ATTEND IF YOU WISH </p> 
       
    </div>
</div>
    
    
</div>

app/views/users/new.html.erb
<div class="signup">
  <div class='nav'> 
    <div class='logo'>  <a class='li'> EventRiteApp </a></div>
    <%= link_to 'Home', root_path, class: 'li check' %>
    <%= link_to 'Sign In', signin_path, class: 'li check' %>
    <%= link_to 'Events', events_path, class: 'li check' %>
   
     </div>
    <%= render 'layouts/error_messages' %>
    <div class="form-group" >
      <%= form_for @user do |f| %>
      
        <%= f.label :name, 'Enter your name' %>
        <%= f.text_field :name , class: 'form-control'%>  
      <br><br>
        <%= f.label :email, 'Enter your email'  %>
        <%= f.email_field :email, class: 'form-control' %>  
        <br><br>
        <%= f.label :password_digest, 'Enter your password'  %>
        <%= f.password_field :password_digest, class: 'form-control' %>
        <br><br>
       
        <%= f.submit  'Create your account' , class: 'btn btn-primary'  %>
      
      <% end %>
    </div>
    
</div>
 

app/views/users/show.html.erb
<% if !@current_user.nil? %>
<%= render 'layouts/headings' %>
<% else %>
<%=  render 'layouts/header2'%>
<% end %>
<div class="greet">
    <h2> Hello <%= @user.name %></h2>
</div>

<div class="index">
<div class="upcoming">
<% if !@events.empty? %>
<h2>Events Created</h2>
<ul>
<% @events.each do |event| %>
<li> <%= link_to event.title , event %></li>
 
<% end %>
</ul>
   <br>
<% else %>
<h3>No Created Events</h3>

<% end %>  
</div>

 

<div>
<% if @invitations.empty? %>
<h3>No invitations</h3>
<% end %>

<% if !@invites.empty? %>

<% if !@upcoming_events.empty? %>
<ul>
<h2>Events Invited To:</h2>


<% @upcoming_events.each do |event| %> 
  <li><%= link_to event.title , event %> </li>
<% end %>
</ul>

<% end %>


<% if !@previous_events.empty? %>
<ul>
  <h2>You attended the following events:</h2>
  
  
  <% @previous_events.each do |event| %> 
    <li><%= link_to event.title , event %> </li>
  <% end %>
</ul>

<% end %>

<% end %>
</div>
</div>